# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
-  stage: Build
   jobs:
   - job: Build
     steps:
     - bash: echo Hello Build
     - bash: echo $(PipelineLevelVariable)
     - bash: echo $(Build.BuildId)
     - bash: echo $(Build.BinariesDirectory)
     - bash: echo $(Agent.OS)
     - bash: echo $(Environment.Name)
       displayName: 'Run a one-line script'
-  stage: Staging
   dependsOn: Build
   jobs:
   - job: Staging
     steps:
     - script:
         echo Hello Staging
-  stage: Dev
   variables:
     environment: Dev
   dependsOn: Build
   jobs:
   - job: Dev
     steps:
     - script:
        echo Hello Dev
        echo $(environment)Dev
-  stage: Deploy
   dependsOn:
   - Staging
   - Dev
   jobs:
   - job: Deploy
     steps:
     - script:
         echo Hello Deploy
         echo Add other tasks to build, test, and deploy your project.
         echo See https://aka.ms/yaml
       displayName: 'Run a multi-line script'

#jobs:
#- job: Job1
#  steps:
#  - script: echo Hello job1, world!
#    displayName: 'Run a one-line script'
#- job: Job2
#  dependsOn: Job1
#  steps:
#  - script:
#      echo Hello job2, world!
#      echo Add other tasks to build, test, and deploy your project.
#      echo See https://aka.ms/yaml
#    displayName: 'Run a multi-line script'