trigger:
- main

strategy:
  matrix:
    linux:
      OperatingSystem: 'ubuntu-latest'
    mac:
      OperatingSystem: 'macos-latest'
    windows:
      OperatingSystem: 'windows-latest'  
      
pool:
  vmImage: $(OperatingSystem)

steps:
- script: echo Hello, world running on $(OperatingSystem)
  displayName: 'Run a one-line script'